// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTo4yHGq9jPxf0Bj_O_s6weTNUwBjw3gs',
    appId: '1:370206523698:web:f96e4696d82ec083e6d72b',
    messagingSenderId: '370206523698',
    projectId: 'flutter-chat-application1',
    authDomain: 'flutter-chat-application1.firebaseapp.com',
    storageBucket: 'flutter-chat-application1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_mchNhYzALDKPBCTu7PvmtRrm_lHPIzw',
    appId: '1:370206523698:android:79635371de0be3c5e6d72b',
    messagingSenderId: '370206523698',
    projectId: 'flutter-chat-application1',
    storageBucket: 'flutter-chat-application1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGh2F3y_rixUKuRKtBuoQ31gB97gtV-HM',
    appId: '1:370206523698:ios:c6a1f5b988c512cee6d72b',
    messagingSenderId: '370206523698',
    projectId: 'flutter-chat-application1',
    storageBucket: 'flutter-chat-application1.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGh2F3y_rixUKuRKtBuoQ31gB97gtV-HM',
    appId: '1:370206523698:ios:9c5d3495b58aef7be6d72b',
    messagingSenderId: '370206523698',
    projectId: 'flutter-chat-application1',
    storageBucket: 'flutter-chat-application1.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
